import { registerTool } from "./ag-ui-client"
import {
  MetricCard,
  Chart,
  DataTable,
  DataGrid,
  ConfirmationCard,
  UserForm,
  ToggleSwitch,
  InfoBanner,
  ProgressBar,
  AvatarCard,
  Timeline,
  MultiStepForm,
  SearchWithFilters,
  DateTimeRangePicker,
  RatingSelector,
  KanbanBoard,
  ChecklistWithProgress,
  ApprovalWorkflowCard,
  TeamMemberList,
  ProductCatalogGrid,
  CartSummaryPanel,
  PaymentDetailsForm,
  MessageFeed,
  OrderStatusTracker,
  EditableDataTable,
  CrudDataTable,
  ExpandableRowTable,
  ColumnToggleTable,
  LocationMap,
  RoutePlannerMap,
  ThreadedComments,
  MentionInput,
  TabLayout,
  AccordionContent,
  MarkdownRenderer,
  CodeSnippetViewer,
  ColorPickerPopover,
  ImageGallery,
  EnvironmentSwitcher,
  LanguageSelector,
  ThemeToggle,
  ToastStack,
  ModalPrompt,
  OrgChartViewer,
  AIPromptBuilder,
} from "./components"

// Create a registry object to export
export const registry = {
  MetricCard,
  Chart,
  DataTable,
  DataGrid,
  ConfirmationCard,
  UserForm,
  ToggleSwitch,
  InfoBanner,
  ProgressBar,
  AvatarCard,
  Timeline,
  MultiStepForm,
  SearchWithFilters,
  DateTimeRangePicker,
  RatingSelector,
  KanbanBoard,
  ChecklistWithProgress,
  ApprovalWorkflowCard,
  TeamMemberList,
  ProductCatalogGrid,
  CartSummaryPanel,
  PaymentDetailsForm,
  MessageFeed,
  OrderStatusTracker,
  EditableDataTable,
  CrudDataTable,
  ExpandableRowTable,
  ColumnToggleTable,
  LocationMap,
  RoutePlannerMap,
  ThreadedComments,
  MentionInput,
  TabLayout,
  AccordionContent,
  MarkdownRenderer,
  CodeSnippetViewer,
  ColorPickerPopover,
  ImageGallery,
  EnvironmentSwitcher,
  LanguageSelector,
  ThemeToggle,
  ToastStack,
  ModalPrompt,
  OrgChartViewer,
  AIPromptBuilder,
}

/**
 * Registers all agentic UI components with the AG-UI protocol
 * This makes all components available for agents to use
 */
export function registerAllAgentComponents() {
  console.log("Registering all agent components...")

  // Create a map of component names to components
  const componentMap = {
    // Ensure all component names are lowercase for consistency
    metriccard: MetricCard,
    chart: Chart,
    datatable: DataTable,
    datagrid: DataGrid,
    confirmationcard: ConfirmationCard,
    userform: UserForm,
    toggleswitch: ToggleSwitch,
    infobanner: InfoBanner,
    progressbar: ProgressBar,
    avatarcard: AvatarCard,
    timeline: Timeline,
    multistepform: MultiStepForm,
    searchwithfilters: SearchWithFilters,
    datetimerangepicker: DateTimeRangePicker,
    ratingselector: RatingSelector,
    kanbanboard: KanbanBoard,
    checklistwithprogress: ChecklistWithProgress,
    approvalworkflowcard: ApprovalWorkflowCard,
    teammemberlist: TeamMemberList,
    productcataloggrid: ProductCatalogGrid,
    cartsummarypanel: CartSummaryPanel,
    paymentdetailsform: PaymentDetailsForm,
    messagefeed: MessageFeed,
    orderstatustracker: OrderStatusTracker,
    editabledatatable: EditableDataTable,
    cruddatatable: CrudDataTable,
    expandablerowtable: ExpandableRowTable,
    columntoggletable: ColumnToggleTable,
    locationmap: LocationMap,
    routeplannermap: RoutePlannerMap,
    threadedcomments: ThreadedComments,
    mentioninput: MentionInput,
    tablayout: TabLayout,
    accordioncontent: AccordionContent,
    markdownrenderer: MarkdownRenderer,
    codesnippetviewer: CodeSnippetViewer,
    colorpickerpopover: ColorPickerPopover,
    imagegallery: ImageGallery,
    environmentswitcher: EnvironmentSwitcher,
    languageselector: LanguageSelector,
    themetoggle: ThemeToggle,
    toaststack: ToastStack,
    modalprompt: ModalPrompt,
    orgchartviewer: OrgChartViewer,
    aipromptbuilder: AIPromptBuilder,
  }

  console.log("Components to register:", Object.keys(componentMap).length)

  // Register each component and log for debugging
  Object.entries(componentMap).forEach(([name, Component]) => {
    registerTool(name, Component)
    console.log(`Registered component: ${name}`)
  })

  console.log("All components registered successfully")
}
